### PR TITLE
Fix within subnet construction

### LINKED ISSUE #27: Within subnet is wrong unless block names are well-behaved
When performing within estimation, lighthergm reorders the edges and nodes into a block-diagonal matrix. When doing that, it obtains the subgraph for each block by looping here:
https://github.com/sansan-inc/lighthergm/blob/32dc3ea01e9f88151143ca5344f20134baf1afa0/lighthergm/R/estimate_within_params.R#L87

That loop goes from 1 to the number of clusters. If you have four clusters, then the value of `k` there takes any of 1, 2, 3, 4. Then the list of nodes is filtered by the `get_induced_subgraph` function. The problem is the filter here:
https://github.com/sansan-inc/lighthergm/blob/32dc3ea01e9f88151143ca5344f20134baf1afa0/lighthergm/R/estimate_within_params.R#L216

It only works well if the block names are 1, 2, 3 or 4 (as in the previous example). This assumption is not always met. For example, if you extract the subnetwork formed by blocks 2 and 3, you'd have two blocks, and `k` would only take the values 1 and 2, thus ignoring block 3 when estimating within parameters.

The loop should use the names of the blocks instead of their relative position.

### PR DESCRIPTION
**Pull request by justinian336**
Closes #27 
Fixed the within-block estimation so that the loop iterates over the block names instead of their indices.
Added a test to check that the network and the block assignments after estimation is correct. The test should fail if the something other than the block names are used.

### CODE REVIEW

File: lighthergm/R/estimate_within_params.R [hunk 1]
```diff
@@ -33,6 +33,7 @@ estimate_within_params <-
       )
 
     # Get number of clusters
+    all_clusters <- names(table(factor(block_structure$block)))
     n_cluster <- length(unique(z_memb))
```
Comment (komatsuna4747) [inline lighthergm/R/estimate_within_params.R]:
```suggestion 
```
This line is no longer necessary and can be deleted.

**Review by komatsuna4747 — APPROVED** [review]
LGTM 👍 I left one comment.

**Comment by justinian336** [comment]
@komatsuna4747 Thanks for the review! I made the change you suggested. The checks passed again, so I'm merging.
